/**
 * Flag data for the locale picker — one vendored 4x3 SVG per locale, inlined
 * as inner markup so SSR and the Worker can render it without a fetch.
 *
 * Three modules, because the bodies are ~115 KB and the map is 300 bytes:
 *
 *   flag-countries.mjs  locale → country, `flagCountryFor` — what the Solid
 *                       menu imports statically (it names symbols by country)
 *   flag-bodies.mjs     the SVG markup by country — imported statically by the
 *                       server build only; the browser build reaches it through
 *                       a dynamic import() taken solely when a flag menu renders
 *                       without server HTML
 *   flags.mjs           the public `@devslab/site-kit/flags` subpath, composing
 *                       both — its API is unchanged for consumers
 *
 * Flags live here, not in dds-icons: that set's check-icons.mjs bans colour
 * literals and requires stroke="currentColor", which a flag cannot satisfy.
 *
 *   node scripts/build-flags.mjs          write the three modules + .d.mts
 *   node scripts/build-flags.mjs --check  fail if the committed output is stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkg = join(dirname(fileURLToPath(import.meta.url)), "..");
const FLAG_COUNTRY = {
  ko: "kr", en: "us", ja: "jp", "zh-HK": "hk", "zh-TW": "tw", hi: "in", vi: "vn",
  id: "id", th: "th", "pt-BR": "br", fr: "fr", de: "de", es: "es", ar: "sa",
};
const HEADER =
  "/* Generated by scripts/build-flags.mjs — do not edit. Source: flags/*.svg (flag-icons, MIT). Copyright (c) 2013 Panayiotis Lipiridis */";

const entries = Object.entries(FLAG_COUNTRY).map(([locale, country]) => {
  // Normalise the line endings we read, not just the ones we write. A
  // Windows checkout with core.autocrlf hands these files back as CRLF,
  // JSON.stringify faithfully preserves that as \r\n escapes, and the
  // generated module then differs from the one CI generates on Linux —
  // --check fails there and passes here, and every flag body ships an
  // extra 2.8 KB of carriage returns to the browser. A generator is only
  // reproducible if what it reads is byte-stable across checkouts.
  const text = readFileSync(join(pkg, "flags", `${country}.svg`), "utf8").replaceAll("\r\n", "\n").trim();
  const open = text.match(/^<svg\b[^>]*>/);
  if (!open) throw new Error(`flags/${country}.svg: no <svg> root`);
  const viewBox = open[0].match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`flags/${country}.svg: no viewBox`);
  const body = text.replace(/^<svg\b[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  if (/<script|on[a-z]+=/i.test(body)) throw new Error(`flags/${country}.svg: active content`);
  if (/\bid='/.test(body)) throw new Error(`flags/${country}.svg: id attribute must be double-quoted`);
  for (const match of body.matchAll(/\bid="([^"]*)"/g)) {
    if (!/^[\w-]+$/.test(match[1])) throw new Error(`flags/${country}.svg: unsafe id attribute value: ${match[1]}`);
  }
  return { locale, country, viewBox, body };
});

const viewBoxes = new Set(entries.map((e) => e.viewBox));
if (viewBoxes.size !== 1) throw new Error(`flags must share one viewBox so a <use> can reference any symbol: ${[...viewBoxes].join(", ")}`);
const [FLAG_VIEWBOX] = viewBoxes;

// One entry per country, not per locale: seven Indian languages would
// otherwise inline the same India SVG seven times.
const byCountry = [...new Map(entries.map((e) => [e.country, e])).values()];

const countriesJs = `${HEADER}
export const FLAG_COUNTRY = Object.freeze(${JSON.stringify(FLAG_COUNTRY, null, 2)});

/** Every vendored flag is 4:3 on this box, so any <use> can point at any symbol. */
export const FLAG_VIEWBOX = ${JSON.stringify(FLAG_VIEWBOX)};

const VENDORED = new Set(Object.values(FLAG_COUNTRY));

/**
 * The country whose flag stands for a locale — a family locale through
 * FLAG_COUNTRY, a product's own through its registry's \`flagCountry\`.
 * Same lookup order and errors as \`flagFor\`, without loading a body.
 *
 * @param {string} locale
 * @param {{ LOCALES?: ReadonlyArray<{ code: string, flagCountry?: string }> }} [registry]
 * @returns {string}
 */
export function flagCountryFor(locale, registry) {
  const country = FLAG_COUNTRY[locale];
  if (country) return country;
  const extra = registry?.LOCALES?.find((definition) => definition.code === locale);
  if (extra?.flagCountry) {
    if (VENDORED.has(extra.flagCountry)) return extra.flagCountry;
    throw new RangeError(\`No vendored flag for country: \${extra.flagCountry} (locale \${locale})\`);
  }
  throw new RangeError(\`No flag for locale: \${locale}\`);
}
`;
const countriesDts = `${HEADER}
import type { LocaleRegistry } from "./locales.mjs";
import type { SiteLocale } from "./locales.mjs";
export declare const FLAG_COUNTRY: Readonly<Record<SiteLocale, string>>;
export declare const FLAG_VIEWBOX: string;
export declare function flagCountryFor(locale: string, registry?: LocaleRegistry<string>): string;
`;

const bodiesJs = `${HEADER}
/**
 * Flags indexed by country, not by locale.
 *
 * A locale-keyed map can only answer for languages the family ships. A
 * product that adds its own — BookLinq sells in six Indian languages the
 * family does not carry — names a country here instead, so nobody vendors
 * a second copy of an SVG this package already has.
 */
export const FLAGS_BY_COUNTRY = Object.freeze({
${byCountry.map((e) => `  ${JSON.stringify(e.country)}: Object.freeze({ country: ${JSON.stringify(e.country)}, viewBox: ${JSON.stringify(e.viewBox)}, body: ${JSON.stringify(e.body)} }),`).join("\n")}
});
`;
const bodiesDts = `${HEADER}
export interface LocaleFlag { readonly country: string; readonly viewBox: string; readonly body: string }
export declare const FLAGS_BY_COUNTRY: Readonly<Record<string, LocaleFlag>>;
`;

const js = `${HEADER}
import { FLAG_COUNTRY, FLAG_VIEWBOX, flagCountryFor } from "./flag-countries.mjs";
import { FLAGS_BY_COUNTRY } from "./flag-bodies.mjs";

export { FLAG_COUNTRY, FLAG_VIEWBOX, flagCountryFor, FLAGS_BY_COUNTRY };

export const LOCALE_FLAGS = Object.freeze({
${entries.map((e) => `  ${JSON.stringify(e.locale)}: FLAGS_BY_COUNTRY[${JSON.stringify(e.country)}],`).join("\n")}
});

/**
 * @param {string} locale
 * @param {{ LOCALES?: ReadonlyArray<{ code: string, flagCountry?: string }> }} [registry]
 *   A product's locale registry, for a locale the family does not carry.
 *   Its \`flagCountry\` names one of FLAGS_BY_COUNTRY.
 */
export function flagFor(locale, registry) {
  const flag = LOCALE_FLAGS[locale];
  if (flag) return flag;
  const extra = registry?.LOCALES?.find((definition) => definition.code === locale);
  if (extra?.flagCountry) {
    const vendored = FLAGS_BY_COUNTRY[extra.flagCountry];
    if (vendored) return vendored;
    throw new RangeError(\`No vendored flag for country: \${extra.flagCountry} (locale \${locale})\`);
  }
  throw new RangeError(\`No flag for locale: \${locale}\`);
}
`;
const dts = `${HEADER}
import type { LocaleRegistry } from "./locales.mjs";
import type { SiteLocale } from "./locales.mjs";
import type { LocaleFlag } from "./flag-bodies.mjs";
export type { LocaleFlag };
export { FLAG_COUNTRY, FLAG_VIEWBOX, flagCountryFor } from "./flag-countries.mjs";
export { FLAGS_BY_COUNTRY } from "./flag-bodies.mjs";
export declare const LOCALE_FLAGS: Readonly<Record<SiteLocale, LocaleFlag>>;
export declare function flagFor(locale: string, registry?: LocaleRegistry<string>): LocaleFlag;
`;

const targets = [
  ["src/core/flag-countries.mjs", countriesJs], ["src/core/flag-countries.d.mts", countriesDts],
  ["src/core/flag-bodies.mjs", bodiesJs], ["src/core/flag-bodies.d.mts", bodiesDts],
  ["src/core/flags.mjs", js], ["src/core/flags.d.mts", dts],
];
if (process.argv.includes("--check")) {
  const stale = targets.filter(([rel, next]) => { try { return readFileSync(join(pkg, rel), "utf8") !== next; } catch { return true; } });
  if (stale.length) { console.error(`flags out of date: ${stale.map(([r]) => r).join(", ")} — run build-flags`); process.exit(1); }
  console.log(`site-kit flags: ${entries.length} locales over ${byCountry.length} countries, in sync`);
} else {
  for (const [rel, next] of targets) writeFileSync(join(pkg, rel), next);
  console.log(`site-kit flags: wrote ${targets.length} files (${entries.length} locales, ${byCountry.length} countries)`);
}
