/**
 * Flag data for the locale picker — one vendored 4x3 SVG per locale, inlined
 * as inner markup so SSR and the Worker can render it without a fetch.
 *
 * Flags live here, not in dds-icons: that set's check-icons.mjs bans colour
 * literals and requires stroke="currentColor", which a flag cannot satisfy.
 *
 *   node scripts/build-flags.mjs          write src/core/flags.mjs + .d.mts
 *   node scripts/build-flags.mjs --check  fail if the committed output is stale
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkg = join(dirname(fileURLToPath(import.meta.url)), "..");
const FLAG_COUNTRY = {
  ko: "kr", en: "us", ja: "jp", "zh-HK": "hk", "zh-TW": "tw", hi: "in", vi: "vn",
  id: "id", th: "th", "pt-BR": "br", fr: "fr", de: "de", es: "es", ar: "sa",
};
const HEADER = "/* Generated by scripts/build-flags.mjs — do not edit. Source: flags/*.svg (flag-icons, MIT) */";

const entries = Object.entries(FLAG_COUNTRY).map(([locale, country]) => {
  const text = readFileSync(join(pkg, "flags", `${country}.svg`), "utf8").trim();
  const open = text.match(/^<svg\b[^>]*>/);
  if (!open) throw new Error(`flags/${country}.svg: no <svg> root`);
  const viewBox = open[0].match(/viewBox="([^"]+)"/)?.[1];
  if (!viewBox) throw new Error(`flags/${country}.svg: no viewBox`);
  const body = text.replace(/^<svg\b[^>]*>/, "").replace(/<\/svg>\s*$/, "").trim();
  if (/<script|on[a-z]+=/i.test(body)) throw new Error(`flags/${country}.svg: active content`);
  return { locale, country, viewBox, body };
});

const js = `${HEADER}
export const FLAG_COUNTRY = Object.freeze(${JSON.stringify(FLAG_COUNTRY, null, 2)});

export const LOCALE_FLAGS = Object.freeze({
${entries.map((e) => `  ${JSON.stringify(e.locale)}: Object.freeze({ country: ${JSON.stringify(e.country)}, viewBox: ${JSON.stringify(e.viewBox)}, body: ${JSON.stringify(e.body)} }),`).join("\n")}
});

export function flagFor(locale) {
  const flag = LOCALE_FLAGS[locale];
  if (!flag) throw new RangeError(\`No flag for locale: \${locale}\`);
  return flag;
}
`;
const dts = `${HEADER}
import type { SiteLocale } from "./locales.mjs";
export interface LocaleFlag { readonly country: string; readonly viewBox: string; readonly body: string }
export declare const FLAG_COUNTRY: Readonly<Record<SiteLocale, string>>;
export declare const LOCALE_FLAGS: Readonly<Record<SiteLocale, LocaleFlag>>;
export declare function flagFor(locale: SiteLocale): LocaleFlag;
`;

const targets = [["src/core/flags.mjs", js], ["src/core/flags.d.mts", dts]];
if (process.argv.includes("--check")) {
  const stale = targets.filter(([rel, next]) => readFileSync(join(pkg, rel), "utf8") !== next);
  if (stale.length) { console.error(`flags out of date: ${stale.map(([r]) => r).join(", ")} — run build-flags`); process.exit(1); }
  console.log("site-kit flags: 14 locales, generated output in sync");
} else {
  for (const [rel, next] of targets) writeFileSync(join(pkg, rel), next);
  console.log("site-kit flags: wrote src/core/flags.mjs and flags.d.mts (14 locales)");
}
