/**
 * The family font (D-033) — Geist, Geist Mono and Pretendard as self-hostable
 * woff2, with one stylesheet whose family names are the token's names.
 *
 *   fonts/<dir>/*.woff2      the faces, byte-for-byte as upstream ships them
 *   fonts/<dir>/LICENSE.txt  each upstream's SIL Open Font License text
 *   fonts/manifest.json      where every file came from: package, version,
 *                            tarball integrity, bytes, sha256, unicode-range
 *   fonts.css                generated from the manifest — never edit by hand
 *
 *   node scripts/build-fonts.mjs           rewrite fonts.css from the manifest
 *   node scripts/build-fonts.mjs --check   fail if fonts.css, a woff2 or a
 *                                          license differs from the manifest,
 *                                          or fonts/ holds a file it does not
 *                                          list (no network, built-ins only)
 *   node scripts/build-fonts.mjs --vendor  fetch the pinned upstream tarballs
 *                                          from the npm registry, verify their
 *                                          integrity, and rewrite fonts/ + the
 *                                          manifest + fonts.css (maintainers,
 *                                          when bumping a version below)
 *
 * The faces are upstream's own subsets, never re-cut here. Pretendard is
 * licensed with the Reserved Font Name "Pretendard": a modified version (a
 * subset we made ourselves would be one) may not carry that name. The
 * author's dynamic-subset build is unmodified, so it may.
 */
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { gunzipSync } from "node:zlib";

const pkg = join(dirname(fileURLToPath(import.meta.url)), "..");
const fontsDir = join(pkg, "fonts");
const manifestPath = join(fontsDir, "manifest.json");
const cssPath = join(pkg, "fonts.css");

/**
 * The faces the family ships. `family` is the CSS name, and it is the name
 * the DDS tokens already use (`--dds-font-family-sans` / `-mono`), so a page
 * that loads fonts.css gets these files through the token stack unchanged.
 * Normal style only: the products set no italic text today, and a browser
 * slants the upright face when one asks.
 */
const FAMILIES = [
  {
    family: "Geist",
    dir: "geist",
    source: { package: "@fontsource-variable/geist", version: "5.3.0" },
    css: "index.css",
    license: "LICENSE",
  },
  {
    family: "Geist Mono",
    dir: "geist-mono",
    source: { package: "@fontsource-variable/geist-mono", version: "5.3.0" },
    css: "index.css",
    license: "LICENSE",
  },
  {
    family: "Pretendard",
    dir: "pretendard",
    source: { package: "pretendard", version: "1.3.9" },
    css: "dist/web/variable/pretendardvariable-dynamic-subset.css",
    license: "dist/LICENSE.txt",
  },
];

const sha256 = (bytes) => createHash("sha256").update(bytes).digest("hex");
const posix = (path) => path.replaceAll("\\", "/");

/** The stylesheet for a manifest. Pure: the same manifest gives the same bytes everywhere. */
export function renderFontsCss(manifest) {
  const header = [
    "/* Generated by scripts/build-fonts.mjs from fonts/manifest.json — do not edit (D-033).",
    " *",
    " * The DevsLab family font, self-hosted. Each url() is relative to this file,",
    " * so a bundler copies the woff2 into the product's own assets and the page",
    " * fetches them from its own origin (font-src 'self').",
    " *",
    ...manifest.families.map(
      (f) => ` * ${f.family}: ${f.source.package}@${f.source.version}, ${f.source.license} — fonts/${f.dir}/LICENSE.txt`,
    ),
    " */",
  ].join("\n");
  const blocks = manifest.families.flatMap((f) =>
    f.faces.map((face) =>
      [
        "@font-face {",
        `  font-family: "${f.family}";`,
        "  font-style: normal;",
        `  font-weight: ${f.weight};`,
        "  font-display: swap;",
        `  src: url("./fonts/${f.dir}/${face.file}") format("woff2");`,
        `  unicode-range: ${face.unicodeRange};`,
        "}",
      ].join("\n"),
    ),
  );
  return `${header}\n\n${blocks.join("\n\n")}\n`;
}

/** Every @font-face of an upstream stylesheet: file name, weight range, unicode-range. */
function parseUpstreamCss(text, label) {
  const faces = [];
  for (const block of text.matchAll(/@font-face\s*\{([^}]*)\}/g)) {
    const body = block[1];
    const style = body.match(/font-style:\s*([^;]+);/)?.[1].trim();
    if (style !== "normal") continue;
    const url = body.match(/src:\s*url\(\s*['"]?([^'")]+)['"]?\s*\)/)?.[1];
    const weight = body.match(/font-weight:\s*([^;]+);/)?.[1].trim();
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1].trim();
    if (!url || !weight || !range) throw new Error(`${label}: an @font-face without src, weight or unicode-range`);
    faces.push({ path: url.replace(/^\.\//, ""), weight, unicodeRange: range.split(/\s*,\s*/).join(", ") });
  }
  if (faces.length === 0) throw new Error(`${label}: no normal-style @font-face`);
  return faces;
}

/** A gzip'd npm tarball's regular files, keyed by path with the leading `package/` removed. */
function untar(gz) {
  const tar = gunzipSync(gz);
  const files = new Map();
  let offset = 0;
  let longName = null;
  while (offset + 512 <= tar.length) {
    const header = tar.subarray(offset, offset + 512);
    if (header.every((byte) => byte === 0)) break;
    const field = (start, length) => header.subarray(start, start + length).toString("utf8").replace(/\0.*$/s, "");
    const size = Number.parseInt(field(124, 12).trim() || "0", 8);
    const type = field(156, 1);
    const prefix = field(345, 155);
    let name = longName ?? (prefix ? `${prefix}/${field(0, 100)}` : field(0, 100));
    longName = null;
    const data = tar.subarray(offset + 512, offset + 512 + size);
    if (type === "L") longName = data.toString("utf8").replace(/\0.*$/s, "");
    else if (type === "x") longName = data.toString("utf8").match(/^\d+ path=(.*)$/m)?.[1] ?? null;
    else if (type === "0" || type === "") files.set(name.replace(/^[^/]+\//, ""), Buffer.from(data));
    offset += 512 + Math.ceil(size / 512) * 512;
  }
  return files;
}

async function fetchTarball({ package: name, version }) {
  const meta = await (await fetch(`https://registry.npmjs.org/${name.replace("/", "%2F")}/${version}`)).json();
  const { tarball, integrity } = meta.dist ?? {};
  if (!tarball || !integrity?.startsWith("sha512-")) throw new Error(`${name}@${version}: no tarball or sha512 integrity in the registry`);
  const bytes = Buffer.from(await (await fetch(tarball)).arrayBuffer());
  const actual = `sha512-${createHash("sha512").update(bytes).digest("base64")}`;
  if (actual !== integrity) throw new Error(`${name}@${version}: tarball integrity mismatch`);
  return { files: untar(bytes), integrity, license: meta.license };
}

async function vendor() {
  rmSync(fontsDir, { recursive: true, force: true });
  const families = [];
  for (const spec of FAMILIES) {
    const { files, integrity, license } = await fetchTarball(spec.source);
    const cssText = files.get(spec.css)?.toString("utf8");
    if (!cssText) throw new Error(`${spec.source.package}: ${spec.css} not in the tarball`);
    const upstream = parseUpstreamCss(cssText, `${spec.source.package}/${spec.css}`);
    const weights = new Set(upstream.map((face) => face.weight));
    if (weights.size !== 1) throw new Error(`${spec.source.package}: faces disagree on the weight range`);
    const out = join(fontsDir, spec.dir);
    mkdirSync(out, { recursive: true });
    const cssDir = posix(dirname(spec.css)) === "." ? "" : `${posix(dirname(spec.css))}/`;
    const faces = upstream.map((face) => {
      const bytes = files.get(`${cssDir}${face.path}`);
      if (!bytes) throw new Error(`${spec.source.package}: ${cssDir}${face.path} not in the tarball`);
      const file = face.path.split("/").at(-1);
      writeFileSync(join(out, file), bytes);
      return { file, bytes: bytes.length, sha256: sha256(bytes), unicodeRange: face.unicodeRange };
    });
    const licenseText = files.get(spec.license);
    if (!licenseText) throw new Error(`${spec.source.package}: ${spec.license} not in the tarball`);
    const normalisedLicense = Buffer.from(licenseText.toString("utf8").replaceAll("\r\n", "\n"));
    writeFileSync(join(out, "LICENSE.txt"), normalisedLicense);
    families.push({
      family: spec.family,
      dir: spec.dir,
      weight: [...weights][0],
      source: { ...spec.source, integrity, license },
      license: { file: "LICENSE.txt", sha256: sha256(normalisedLicense) },
      faces,
    });
  }
  const manifest = { generatedBy: "scripts/build-fonts.mjs --vendor", families };
  writeFileSync(manifestPath, `${JSON.stringify(manifest, null, 2)}\n`);
  writeFileSync(cssPath, renderFontsCss(manifest));
  const total = families.reduce((sum, f) => sum + f.faces.length, 0);
  console.log(`vendored ${total} faces into fonts/ and rewrote fonts.css`);
}

function check() {
  const errors = [];
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  const expectedCss = renderFontsCss(manifest);
  const actualCss = existsSync(cssPath) ? readFileSync(cssPath, "utf8").replaceAll("\r\n", "\n") : "";
  if (actualCss !== expectedCss) errors.push("fonts.css differs from the manifest — run node scripts/build-fonts.mjs");
  const families = new Map(FAMILIES.map((f) => [f.dir, f]));
  for (const family of manifest.families) {
    const spec = families.get(family.dir);
    if (!spec || spec.family !== family.family || spec.source.version !== family.source.version) {
      errors.push(`manifest family ${family.dir} does not match FAMILIES — run with --vendor`);
    }
    const dir = join(fontsDir, family.dir);
    const listed = new Set([family.license.file, ...family.faces.map((face) => face.file)]);
    for (const name of existsSync(dir) ? readdirSync(dir) : []) {
      if (!listed.has(name)) errors.push(`fonts/${family.dir}/${name} is not in the manifest`);
    }
    for (const face of family.faces) {
      const path = join(dir, face.file);
      if (!existsSync(path)) { errors.push(`fonts/${family.dir}/${face.file} is missing`); continue; }
      const bytes = readFileSync(path);
      if (bytes.length !== face.bytes || sha256(bytes) !== face.sha256) errors.push(`fonts/${family.dir}/${face.file} differs from the manifest`);
    }
    const licensePath = join(dir, family.license.file);
    if (!existsSync(licensePath) || sha256(readFileSync(licensePath)) !== family.license.sha256) {
      errors.push(`fonts/${family.dir}/${family.license.file} is missing or differs from the manifest`);
    }
  }
  if (manifest.families.length !== FAMILIES.length) errors.push("manifest and FAMILIES list different families");
  for (const name of readdirSync(fontsDir)) {
    if (name !== "manifest.json" && !manifest.families.some((f) => f.dir === name)) errors.push(`fonts/${name} is not a manifest family`);
  }
  if (errors.length) {
    console.error(errors.join("\n"));
    process.exit(1);
  }
  console.log(`fonts.css and ${manifest.families.reduce((sum, f) => sum + f.faces.length, 0)} faces match fonts/manifest.json`);
}

const invokedDirectly = process.argv[1] && resolve(process.argv[1]).toLowerCase() === fileURLToPath(import.meta.url).toLowerCase();
if (invokedDirectly) {
  if (process.argv.includes("--vendor")) await vendor();
  else if (process.argv.includes("--check")) check();
  else {
    writeFileSync(cssPath, renderFontsCss(JSON.parse(readFileSync(manifestPath, "utf8"))));
    console.log("rewrote fonts.css from fonts/manifest.json");
  }
}
