/**
 * dds-icons build — one SVG source, three shipped shapes:
 *
 *   dist/svg/*.svg   the sources, copied verbatim (the set, as files)
 *   dist/icons.svg   one sprite: <symbol id="dds-<name>"> per icon, for
 *                    <use href="…#dds-phone"> on web
 *   dist/icons.js    { name: { viewBox, strokeWidth, body } } + .d.ts —
 *                    for runtimes that build their own element (RN, the
 *                    AskLinq widget's createElementNS renderer, SSR)
 *
 * No per-framework components are generated: spec §2 says framework packages
 * exist only when that framework's product exists. A map of path data is what
 * every consumer can build from today.
 */
import { copyFileSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = dirname(fileURLToPath(import.meta.url));
const svgDir = join(pkgDir, "svg");
const dist = join(pkgDir, "dist");

const HEADER = "/* Generated by @devslab-kr/dds-icons — do not edit. Source: svg/*.svg */";

/** Icon sources: core set in svg/, the devslab.kr-only set in svg/site/.
 *  The `site-` prefix stays part of the name (the folder is organization,
 *  the name is the identity — renaming would break existing references). */
export function readIcons() {
  const files = [
    ...readdirSync(svgDir).filter((f) => f.endsWith(".svg")).map((f) => ["svg", f]),
    ...readdirSync(join(svgDir, "site")).filter((f) => f.endsWith(".svg")).map((f) => ["svg/site", f]),
  ];
  return files
    .map(([dir, file]) => {
      const path = join(pkgDir, dir, file);
      const text = readFileSync(path, "utf8").trim();
      const open = text.match(/^<svg\b[^>]*>/);
      if (!open) throw new Error(`${dir}/${file}: no <svg> root`);
      const attrs = Object.fromEntries(
        [...open[0].matchAll(/([\w:-]+)="([^"]*)"/g)].map((m) => [m[1], m[2]]),
      );
      return {
        name: file.replace(/\.svg$/, ""),
        set: dir === "svg" ? "core" : "site",
        rel: `${dir}/${file}`,
        path,
        attrs,
        body: text.replace(/^<svg\b[^>]*>/, "").replace(/<\/svg>$/, ""),
      };
    })
    .sort((a, b) => a.name.localeCompare(b.name));
}

const isMain = process.argv[1] === fileURLToPath(import.meta.url);
if (isMain) {
  const icons = readIcons();
  rmSync(dist, { recursive: true, force: true });
  mkdirSync(join(dist, "svg", "site"), { recursive: true });

  for (const icon of icons) {
    copyFileSync(icon.path, join(dist, icon.set === "core" ? "svg" : "svg/site", `${icon.name}.svg`));
  }

  const symbols = icons
    .map(
      (i) =>
        `  <symbol id="dds-${i.name}" viewBox="${i.attrs.viewBox}" fill="none" stroke="currentColor" ` +
        `stroke-width="${i.attrs["stroke-width"]}" stroke-linecap="round" stroke-linejoin="round">${i.body}</symbol>`,
    )
    .join("\n");
  writeFileSync(
    join(dist, "icons.svg"),
    `<svg xmlns="http://www.w3.org/2000/svg" style="display:none">\n<!-- Generated by @devslab-kr/dds-icons — do not edit. -->\n${symbols}\n</svg>\n`,
  );

  const entries = icons
    .map(
      (i) =>
        `  ${JSON.stringify(i.name)}: { viewBox: ${JSON.stringify(i.attrs.viewBox)}, ` +
        `strokeWidth: ${JSON.stringify(i.attrs["stroke-width"])}, set: ${JSON.stringify(i.set)}, ` +
        `body: ${JSON.stringify(i.body)} },`,
    )
    .join("\n");
  writeFileSync(join(dist, "icons.js"), `${HEADER}\nexport const icons = {\n${entries}\n};\n`);
  writeFileSync(
    join(dist, "icons.d.ts"),
    `${HEADER}\nexport interface DdsIcon {\n  viewBox: string;\n  strokeWidth: string;\n  set: "core" | "site";\n  /** inner SVG markup — paths only, no <svg> wrapper */\n  body: string;\n}\nexport type DdsIconName =\n${icons.map((i) => `  | ${JSON.stringify(i.name)}`).join("\n")};\nexport declare const icons: Record<DdsIconName, DdsIcon>;\n`,
  );

  console.log(
    `dds-icons: ${icons.length} icons (${icons.filter((i) => i.set === "core").length} core + ` +
      `${icons.filter((i) => i.set === "site").length} site) → dist/svg, dist/icons.svg, dist/icons.js`,
  );
}
