/* Generated by scripts/build-flags.mjs — do not edit. Source: flags/*.svg (flag-icons, MIT). Copyright (c) 2013 Panayiotis Lipiridis */
export interface LocaleFlag { readonly country: string; readonly viewBox: string; readonly body: string }
export declare const FLAGS_BY_COUNTRY: Readonly<Record<string, LocaleFlag>>;
