/* Generated by scripts/build-flags.mjs — do not edit. Source: flags/*.svg (flag-icons, MIT). Copyright (c) 2013 Panayiotis Lipiridis */
import type { LocaleRegistry } from "./locales.mjs";
import type { SiteLocale } from "./locales.mjs";
import type { LocaleFlag } from "./flag-bodies.mjs";
export type { LocaleFlag };
export { FLAG_COUNTRY, FLAG_VIEWBOX, flagCountryFor } from "./flag-countries.mjs";
export { FLAGS_BY_COUNTRY } from "./flag-bodies.mjs";
export declare const LOCALE_FLAGS: Readonly<Record<SiteLocale, LocaleFlag>>;
export declare function flagFor(locale: string, registry?: LocaleRegistry<string>): LocaleFlag;
