/* Generated by scripts/build-flags.mjs — do not edit. Source: flags/*.svg (flag-icons, MIT). Copyright (c) 2013 Panayiotis Lipiridis */
import type { SiteLocale } from "./locales.mjs";
export interface LocaleFlag { readonly country: string; readonly viewBox: string; readonly body: string }
export declare const FLAG_COUNTRY: Readonly<Record<SiteLocale, string>>;
export declare const LOCALE_FLAGS: Readonly<Record<SiteLocale, LocaleFlag>>;
export declare function flagFor(locale: SiteLocale): LocaleFlag;
