/* Generated by scripts/build-flags.mjs — do not edit. Source: flags/*.svg (flag-icons, MIT). Copyright (c) 2013 Panayiotis Lipiridis */
import { FLAG_COUNTRY, FLAG_VIEWBOX, flagCountryFor } from "./flag-countries.mjs";
import { FLAGS_BY_COUNTRY } from "./flag-bodies.mjs";

export { FLAG_COUNTRY, FLAG_VIEWBOX, flagCountryFor, FLAGS_BY_COUNTRY };

export const LOCALE_FLAGS = Object.freeze({
  "ko": FLAGS_BY_COUNTRY["kr"],
  "en": FLAGS_BY_COUNTRY["us"],
  "ja": FLAGS_BY_COUNTRY["jp"],
  "zh-HK": FLAGS_BY_COUNTRY["hk"],
  "zh-TW": FLAGS_BY_COUNTRY["tw"],
  "hi": FLAGS_BY_COUNTRY["in"],
  "vi": FLAGS_BY_COUNTRY["vn"],
  "id": FLAGS_BY_COUNTRY["id"],
  "th": FLAGS_BY_COUNTRY["th"],
  "pt-BR": FLAGS_BY_COUNTRY["br"],
  "fr": FLAGS_BY_COUNTRY["fr"],
  "de": FLAGS_BY_COUNTRY["de"],
  "es": FLAGS_BY_COUNTRY["es"],
  "ar": FLAGS_BY_COUNTRY["sa"],
});

/**
 * @param {string} locale
 * @param {{ LOCALES?: ReadonlyArray<{ code: string, flagCountry?: string }> }} [registry]
 *   A product's locale registry, for a locale the family does not carry.
 *   Its `flagCountry` names one of FLAGS_BY_COUNTRY.
 */
export function flagFor(locale, registry) {
  const flag = LOCALE_FLAGS[locale];
  if (flag) return flag;
  const extra = registry?.LOCALES?.find((definition) => definition.code === locale);
  if (extra?.flagCountry) {
    const vendored = FLAGS_BY_COUNTRY[extra.flagCountry];
    if (vendored) return vendored;
    throw new RangeError(`No vendored flag for country: ${extra.flagCountry} (locale ${locale})`);
  }
  throw new RangeError(`No flag for locale: ${locale}`);
}
