/* Generated by scripts/build-flags.mjs — do not edit. Source: flags/*.svg (flag-icons, MIT). Copyright (c) 2013 Panayiotis Lipiridis */
import type { LocaleRegistry } from "./locales.mjs";
import type { SiteLocale } from "./locales.mjs";
export declare const FLAG_COUNTRY: Readonly<Record<SiteLocale, string>>;
export declare const FLAG_VIEWBOX: string;
export declare function flagCountryFor(locale: string, registry?: LocaleRegistry<string>): string;
