/**
 * DDS token build — one source (../../tokens/*.json, W3C Design Tokens format),
 * four artifacts (backlog P1-1 / spec §2):
 *
 *   dist/tokens.css          CSS custom properties (light on :root, dark on [data-theme="dark"])
 *   dist/tailwind/theme.css  Tailwind v4 @theme
 *   dist/tailwind/preset.js  Tailwind v3 preset (+ preset.cjs)
 *   dist/tokens.ts           TypeScript constants (+ tokens.js / tokens.d.ts)
 *   dist/ionic.css           Ionic theme variable mapping
 *
 * Style Dictionary v4 resolves the token graph ({palette.*} references);
 * emission is done by the small formatters below so every $type in our
 * source has an explicit, reviewed rendering — an unknown $type is a build
 * error, not a silently skipped token.
 *
 * Unit policy: CSS artifacts emit px (rem-equivalent at the 16px root the
 * spec assumes); tokens.ts keeps raw numbers so RN can use them as pt.
 */
import StyleDictionary from "style-dictionary";
import { mkdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const pkgDir = dirname(fileURLToPath(import.meta.url));
const tokensDir = join(pkgDir, "..", "..", "tokens");
const dist = join(pkgDir, "dist");

const HEADER = `/* Generated by @devslab-kr/dds-tokens — do not edit. Source: tokens/*.json */`;

// ---------------------------------------------------------------------------
// Resolve both themes with Style Dictionary
// ---------------------------------------------------------------------------

async function resolve(sources) {
  let captured = null;
  const sd = new StyleDictionary({
    source: sources,
    log: { verbosity: "silent" },
    hooks: {
      formats: {
        "dds/capture": ({ dictionary }) => {
          captured = dictionary.allTokens;
          return "";
        },
      },
    },
    platforms: {
      capture: {
        files: [{ destination: ".capture", format: "dds/capture" }],
        buildPath: join(dist, ".parts") + "/",
      },
    },
  });
  await sd.buildAllPlatforms();
  if (!captured) throw new Error("Style Dictionary did not run the capture format");
  return captured;
}

const lightTokens = await resolve([
  join(tokensDir, "palette.json"),
  join(tokensDir, "foundation.json"),
  join(tokensDir, "semantic.light.json"),
]);
const darkTokens = await resolve([
  join(tokensDir, "palette.json"),
  join(tokensDir, "semantic.dark.json"),
]);
rmSync(join(dist, ".parts"), { recursive: true, force: true });

const val = (t) => t.$value ?? t.value;
const typ = (t) => t.$type ?? t.type;
const varName = (t) => `--dds-${t.path.join("-")}`;
const isPalette = (t) => t.path[0] === "palette";
const semanticColors = (tokens) => tokens.filter((t) => t.path[0] === "color");

// ---------------------------------------------------------------------------
// dist/tokens.css
// ---------------------------------------------------------------------------

function cssDecls(tokens, indent) {
  const lines = [];
  for (const t of tokens) {
    const name = varName(t);
    const v = val(t);
    switch (typ(t)) {
      case "color":
      case "fontFamily":
      case "duration":
        lines.push(`${indent}${name}: ${v};`);
        break;
      case "dimension":
        lines.push(`${indent}${name}: ${v}px;`);
        break;
      case "cubicBezier":
        lines.push(`${indent}${name}: cubic-bezier(${v.join(", ")});`);
        break;
      case "typography":
        lines.push(`${indent}${name}-font-size: ${v.fontSize}px;`);
        lines.push(`${indent}${name}-line-height: ${v.lineHeight}px;`);
        lines.push(`${indent}${name}-font-weight: ${v.fontWeight};`);
        break;
      case "shadow":
        lines.push(`${indent}${name}: ${v.web};`);
        break;
      default:
        throw new Error(`No CSS rendering for $type "${typ(t)}" at ${t.path.join(".")}`);
    }
  }
  return lines.join("\n");
}

// The raw palette is deliberately NOT emitted: components may only reference
// semantic tokens (spec §3.1), and what tokens.css doesn't ship can't be used.
// Theme blocks are attribute selectors (not :root[...]) so any subtree can be
// pinned to either theme (twin panels, theme-fixed embeds) with the same file;
// nesting works because an element only ever matches its own data-theme value.
const tokensCss = `${HEADER}

:root,
[data-theme="light"] {
  color-scheme: light;
${cssDecls(lightTokens.filter((t) => !isPalette(t)), "  ")}
}

[data-theme="dark"] {
  color-scheme: dark;
${cssDecls(semanticColors(darkTokens), "  ")}
}
`;

// ---------------------------------------------------------------------------
// dist/tailwind/theme.css (Tailwind v4) + dist/tailwind/preset.js|.cjs (v3)
//
// Color names keep the full semantic path minus the leading "color"
// (bg-brand → class bg-bg-brand): flattening roles ("brand") collides —
// color.bg.brand and color.text.brand are different values. Colors point at
// the tokens.css variables so utilities follow the runtime theme; everything
// non-color is static and gets baked values. Spacing is not overridden:
// Tailwind's default quarter-rem grid already equals the DDS 4px scale
// (p-1=4px … p-16=64px).
// ---------------------------------------------------------------------------

const twColorName = (t) => t.path.slice(1).join("-");
const typoTokens = lightTokens.filter((t) => typ(t) === "typography");
const radiusTokens = lightTokens.filter((t) => t.path[0] === "radius");
const shadowTokens = lightTokens.filter((t) => t.path[0] === "elevation");
const easingTokens = lightTokens.filter((t) => t.path[1] === "easing");
const durationTokens = lightTokens.filter((t) => t.path[1] === "duration");
const familyTokens = lightTokens.filter((t) => typ(t) === "fontFamily");

const tw4Lines = [];
for (const t of familyTokens) tw4Lines.push(`  --font-${t.path[2]}: ${val(t)};`);
for (const t of semanticColors(lightTokens))
  tw4Lines.push(`  --color-${twColorName(t)}: var(${varName(t)});`);
for (const t of typoTokens) {
  const n = t.path[1];
  const v = val(t);
  tw4Lines.push(`  --text-${n}: ${v.fontSize}px;`);
  tw4Lines.push(`  --text-${n}--line-height: ${v.lineHeight}px;`);
  tw4Lines.push(`  --text-${n}--font-weight: ${v.fontWeight};`);
}
for (const t of radiusTokens) tw4Lines.push(`  --radius-${t.path[1]}: ${val(t)}px;`);
for (const t of shadowTokens) tw4Lines.push(`  --shadow-${t.path[1]}: ${val(t).web};`);
for (const t of easingTokens)
  tw4Lines.push(`  --ease-${t.path[2]}: cubic-bezier(${val(t).join(", ")});`);

const tailwindThemeCss = `${HEADER}
/* Tailwind v4 theme. Import AFTER tokens.css — color utilities resolve
 * through the --dds-* variables so they follow the light/dark theme. */
@theme inline {
${tw4Lines.join("\n")}
}
`;

const presetData = {
  theme: {
    extend: {
      colors: Object.fromEntries(
        semanticColors(lightTokens).map((t) => [twColorName(t), `var(${varName(t)})`])
      ),
      fontFamily: Object.fromEntries(familyTokens.map((t) => [t.path[2], val(t)])),
      fontSize: Object.fromEntries(
        typoTokens.map((t) => {
          const v = val(t);
          return [
            t.path[1],
            [`${v.fontSize}px`, { lineHeight: `${v.lineHeight}px`, fontWeight: `${v.fontWeight}` }],
          ];
        })
      ),
      borderRadius: Object.fromEntries(radiusTokens.map((t) => [t.path[1], `${val(t)}px`])),
      boxShadow: Object.fromEntries(shadowTokens.map((t) => [t.path[1], val(t).web])),
      transitionTimingFunction: Object.fromEntries(
        easingTokens.map((t) => [t.path[2], `cubic-bezier(${val(t).join(", ")})`])
      ),
      transitionDuration: Object.fromEntries(durationTokens.map((t) => [t.path[2], val(t)])),
    },
  },
};

const presetBody = JSON.stringify(presetData, null, 2);
const presetJsHeader = `${HEADER}
/* Tailwind v3 preset. Color values are var(--dds-*) references — include
 * tokens.css on the page so they resolve and follow the theme. */`;
const presetEsm = `${presetJsHeader}
const preset = ${presetBody};
export default preset;
`;
const presetCjs = `${presetJsHeader}
module.exports = ${presetBody};
`;

// ---------------------------------------------------------------------------
// dist/ionic.css
// ---------------------------------------------------------------------------

function hexToRgbTriplet(hex) {
  const n = parseInt(hex.slice(1, 7), 16);
  return `${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}`;
}
const byPath = (tokens, path) => {
  const t = tokens.find((x) => x.path.join(".") === path);
  if (!t) throw new Error(`Token not found: ${path}`);
  return val(t);
};

// Ionic components read --ion-* variables; pointing them at the --dds-*
// variables themes Ionic in both modes with this single file. -rgb/-shade
// values are per-hex, so they use build-time palette values (brand is the
// same hex in both themes; the shade is the mapping's own choice, which is
// where raw palette references are allowed).
const ionicCss = `${HEADER}
/* Ionic theme mapping. Import AFTER tokens.css. */
:root {
  --ion-color-primary: var(--dds-color-bg-brand);
  --ion-color-primary-rgb: ${hexToRgbTriplet(byPath(lightTokens, "color.bg.brand"))};
  --ion-color-primary-contrast: var(--dds-color-text-on-brand);
  --ion-color-primary-contrast-rgb: ${hexToRgbTriplet(byPath(lightTokens, "color.text.on-brand"))};
  --ion-color-primary-shade: ${byPath(lightTokens, "palette.cyan.600")};
  --ion-color-primary-tint: var(--dds-color-bg-brand-hover);

  --ion-color-success: var(--dds-color-status-success);
  --ion-color-warning: var(--dds-color-status-warning);
  --ion-color-danger: var(--dds-color-status-danger);

  --ion-background-color: var(--dds-color-bg-default);
  --ion-text-color: var(--dds-color-text-primary);
  --ion-border-color: var(--dds-color-border-default);
  --ion-font-family: var(--dds-font-family-sans);
}
`;

// ---------------------------------------------------------------------------
// dist/tokens.ts / tokens.js / tokens.d.ts
// ---------------------------------------------------------------------------

function treeFrom(tokens, root) {
  const out = {};
  for (const t of tokens) {
    if (t.path[0] !== root) continue;
    let node = out;
    const rel = t.path.slice(1);
    rel.forEach((seg, i) => {
      if (i === rel.length - 1) node[seg] = val(t);
      else node = node[seg] ??= {};
    });
  }
  return out;
}

// Literal source for both the value emit (JS/TS) and the type emit (d.ts) —
// same walker, so the declaration can never drift from the value.
function literal(v, indent) {
  if (typeof v === "string") return JSON.stringify(v);
  if (typeof v === "number") return String(v);
  if (Array.isArray(v)) return `[${v.map((x) => literal(x, indent)).join(", ")}]`;
  const inner = Object.entries(v)
    .map(([k, x]) => `${indent}  ${JSON.stringify(k)}: ${literal(x, indent + "  ")}`)
    .join(",\n");
  return `{\n${inner}\n${indent}}`;
}

const tsExports = {
  palette: treeFrom(lightTokens, "palette"),
  color: {
    light: treeFrom(lightTokens, "color"),
    dark: treeFrom(darkTokens, "color"),
  },
  fontFamily: treeFrom(lightTokens, "font").family,
  typo: treeFrom(lightTokens, "typo"),
  space: treeFrom(lightTokens, "space"),
  radius: treeFrom(lightTokens, "radius"),
  elevation: treeFrom(lightTokens, "elevation"),
  motion: treeFrom(lightTokens, "motion"),
};

const tsHeader = `// Generated by @devslab-kr/dds-tokens — do not edit. Source: tokens/*.json
// Numbers are unitless: web treats them as px (rem-equivalent at 16px root), RN as pt.`;
const entries = Object.entries(tsExports);
const tokensTs = `${tsHeader}

${entries.map(([k, v]) => `export const ${k} = ${literal(v, "")} as const;`).join("\n\n")}

export const tokens = { ${entries.map(([k]) => k).join(", ")} } as const;
export default tokens;
`;
const tokensJs = `${tsHeader.replace("tokens.ts", "tokens.js")}

${entries.map(([k, v]) => `export const ${k} = ${literal(v, "")};`).join("\n\n")}

export const tokens = { ${entries.map(([k]) => k).join(", ")} };
export default tokens;
`;
const tokensDts = `${tsHeader}

${entries.map(([k, v]) => `export declare const ${k}: ${literal(v, "")};`).join("\n\n")}

export declare const tokens: { ${entries.map(([k]) => `${k}: typeof ${k}`).join("; ")} };
export default tokens;
`;

// ---------------------------------------------------------------------------
// Write everything
// ---------------------------------------------------------------------------

mkdirSync(join(dist, "tailwind"), { recursive: true });
const files = {
  "tokens.css": tokensCss,
  "tailwind/theme.css": tailwindThemeCss,
  "tailwind/preset.js": presetEsm,
  "tailwind/preset.cjs": presetCjs,
  "ionic.css": ionicCss,
  "tokens.ts": tokensTs,
  "tokens.js": tokensJs,
  "tokens.d.ts": tokensDts,
};
for (const [rel, content] of Object.entries(files)) {
  writeFileSync(join(dist, rel), content);
}
console.log(`dds-tokens: built ${Object.keys(files).length} files into dist/`);
